### ISSUE TITLE
Second display missing from BoM

### ISSUE THREAD

**Issue by mongrol** [otem/Raspberry-Pi-Looper-synth-drum-thing#1]
Hi,
Fantastic build btw. It appears to have 2 displays but you only have the Teensy tft in the BoM. Can you add the Pi3 one?

**Comment by paulfehr** [comment]
He says on YouTube that it is a Nintendo DS Screen.

**Comment by otem** [comment]
Whoops, it's added now although I don't think sparkfun stocks them anymore.
